### ISSUE TITLE
Missing `strtod`

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-platform#118]
`val float_of_string` (and the corresponding `Scanf` function) uses `strod` (see the [relevant](https://github.com/ocaml/ocaml/blob/trunk/byterun/floats.c#L146) OCaml code). However It [seems](https://github.com/mirage/mirage-platform/blob/master/xen-posix/src/mini_libc.c#L303) that we do not support it.

**Comment by MagnusS** [comment]
This currently also means that calls to `float_of_string` will compile, but crash the unikernel at runtime.

**Comment by dbuenzli** [comment]
FWIW the algorithms of  [this paper](http://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf) look interesting. A self-contained BSD3 implementation by the author is available [here](https://github.com/google/double-conversion).

**Comment by talex5** [comment]
Interesting. A small self-contained implementation of this would be very welcome. Are there any issues with using C++ code in mirage-xen? I guess it will need some support libraries.

**Comment by hhugo** [comment]
related mantis issue. (`strtod` is locale dependent)
http://caml.inria.fr/mantis/view.php?id=6701

**Comment by yomimono** [comment]
This came up again from a user via `cohttp`: https://github.com/mirage/ocaml-cohttp/blob/master/lib/accept_parser.mly#L45 .

**Comment by timbertson** [comment]
I've also hit this with `yojson`, parsing any JSON data containing a float.

**Comment by dbuenzli** [comment]
New issue with a reference to a new paper http://caml.inria.fr/mantis/view.php?id=7218

**Comment by dbuenzli** [comment]
As follow up to the call. The code I'm using in [`libc-ocaml`](https://github.com/dbuenzli/rpi-boot-ocaml/tree/master/libc-ocaml) is [this one](http://www.netlib.org/fp/dtoa.c). It is what used to be used e.g. in V8 before they switched to grisu, here's the [removal commit](https://github.com/v8/v8/commit/1fafbe760d0d6a820cb).

**Comment by dbuenzli** [comment]
Note also that there is a change log [here](http://www.netlib.org/fp/changes) it may be a good idea to mention which version was picked up.

**Comment by ansiwen** [comment]
same problem here in cohttp in combiation with webmachine: https://bpaste.net/show/607e55d45508

so, will this be fixed? what can we do about it? I need a solution, but I'm not sure how it's going to be fixed. I could help.

**Comment by talex5** [comment]
@ansiwen Thanks for the offer! Someone needs to pick a suitable-licensed, self-contained, not-too-messy C implementation and copy it into mirage-platform here: https://github.com/mirage/mirage-platform/tree/master/xen-posix/src (next to `fmt_fp.c`, which does the other direction).
