### ISSUE TITLE
CFLAGS confusion

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-platform#128]
MiniOS exports (via `pkg-config`) some [CFLAGS](https://github.com/talex5/xen/blob/8a5fbc92726858a965ca485ce40b72215f79b3c3/extras/mini-os/libminios-xen.pc.in#L10) (using `ARCH_CFLAGS`) -- more precisely [x86](https://github.com/talex5/xen/blob/8a5fbc92726858a965ca485ce40b72215f79b3c3/extras/mini-os/arch/x86/arch.mk) and [arm](https://github.com/talex5/xen/blob/8a5fbc92726858a965ca485ce40b72215f79b3c3/extras/mini-os/arch/arm/arch.mk)
- [ ] MiniOS is built with `DEF_FLAGS`, which does not include any optimization level
- [ ] [bindings](https://github.com/mirage/mirage-platform/blob/master/bindings/build.sh#L12), [xen-ocaml](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/build.sh#L7-L22), and [xen-posix](https://github.com/mirage/mirage-platform/blob/master/xen-posix/build.sh#L7-L27) repeat parts of the logic (esp `-fno-stack-protector`, which should be exported from MiniOS) and define some custom CFLAGS... shouldn't this be more unified (and use `pkg-config`)?
- [ ] we should use a good optimization level (or does something not compile with -O3?)

**Comment by hannesm** [comment]
(treat this as a laundry list of my personal notes while not having access to a host with Xen and build system, will extend/modify once I get to my cubieboard again)

**Comment by talex5** [comment]
Mini-OS is built with `debug=n`, which implies `-O3`:

https://github.com/mirage/mirage-xen-minios/blob/7c80d9525efa4e4631044a23779d73ed945c9ef3/install.sh#L8

However, it's up to other projects what level to compile with. We shouldn't force it in the pkg-config file.

`-fno-stack-protector` should be removed from any build files outside of Mini-OS.

**Comment by hannesm** [comment]
@talex5 thanks!

**Comment by yomimono** [comment]
I'm going to close this out although I'm not sure whether it has any outstanding items for action or discussion; please feel free to reopen it if there's something that isn't addressed.
