### ISSUE TITLE
Clock.time () inconsistent on ARM

### ISSUE THREAD

**Issue by MagnusS** [mirage/mirage-platform#136]
Clock.time () / default_clock seems to return monotonic time since the unikernel started running in Xen mode on ARM, while in Unix mode and on x86 (Xen/Unix) it returns seconds since epoch.

**Comment by talex5** [comment]
Xen doesn't currently allow ARM guests to read wall-clock time:

http://wiki.xenproject.org/wiki/Xen_ARM_TODO#Expose_Wallclock_time_to_guests

**Comment by yomimono** [comment]
There's no longer an item on the linked TODO list for wallclock time - perhaps this was implemented and we could re-expose it?  Or perhaps we've already done that, and I missed it?

**Comment by hannesm** [comment]
IIUC, this is an issue in our minios (which lifes in a different repository)?
