### ISSUE TITLE
4.02.2 support for tracing patch

### ISSUE THREAD

**Issue by avsm** [mirage/mirage-platform#137]
The tracing patch in `mirage-xen-ocaml` no longer applies due to significant changes in `minor_gc.c` in ocaml 4.02.2 and so the build fails.

/cc @talex5 : it looks like support has been added for GC hooks in 4.02.2, so I thought I'd leave a bug open since the tracing patch needs to be rewritten.

**Comment by talex5** [comment]
This sounds like good news! I'll take a look...

**Comment by avsm** [comment]
OPAM constraint added in ocaml/opam-repository#4329
