### ISSUE TITLE
Support OCaml 4.02.3

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-platform#142]
The new release of OCaml breaks our patches. See https://github.com/mirage/mirage/pull/440#issuecomment-130341212

**Comment by talex5** [comment]
Even with #138?

**Comment by samoht** [comment]
was it released?

**Comment by talex5** [comment]
It was merged, but I don't think there's been a release since then.

**Comment by samoht** [comment]
The history for v2.3.2 and v2.3.3 and master is completely messed-up. Some patches appear twice with different hashes. I'm almost tempted to force push to master to fix that... Any opinion?

**Comment by avsm** [comment]
That'll really confuse things. Why not just resolve the merge conflict?

**Comment by samoht** [comment]
there is no merge conflict. There is a just a different history for v2.3.2, v2.3.3 and master.

**Comment by avsm** [comment]
I'd avoid a force push and just reconcile master via a merge commit.

**Comment by samoht** [comment]
ie:

- https://github.com/mirage/mirage-platform/compare/v2.3.2...v2.3.3
- https://github.com/mirage/mirage-platform/compare/v2.3.2...master
- https://github.com/mirage/mirage-platform/compare/v2.3.3...master

Seems part of #134 have a different hash in the different release. So ok, I'll not force push and just forget about it :-)

**Comment by hannesm** [comment]
if I read this issue correctly, it can be closed now that 2.3.4 is released!?

**Comment by avsm** [comment]
Yep, fixed in 2.3.4
