### ISSUE TITLE
appveyor tests seem not to work

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-platform#174]
They used to work: https://ci.appveyor.com/project/djs55/mirage-platform/build/1.0.38 is the passing test for https://github.com/mirage/mirage-platform/pull/165 from May of this year, but it appears that no PR since then has successfully built on Appveyor.

It appears to my untrained eye that the combination of us not setting `PACKAGE` and there not being a single `opam` file for this repository are causing the usual build path to fail.

**Comment by yomimono** [comment]
I've done a bit of test maintenance in https://github.com/mirage/mirage-platform/pull/183; as of https://ci.appveyor.com/project/djs55/mirage-platform/build/1.0.79 , the tests are still failing but seem to be doing so with useful information:

```
opam install mirage-xen-posix --deps-only
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mirage-xen-posix: git] Command started
[mirage-xen-posix: git] Command started
[mirage-xen-posix] git+file://C:\projects\mirage-platform already up-to-date
The following dependencies couldn't be met:
  - mirage-xen-posix -> mirage-xen-minios >= 0.7.0
Your request can't be satisfied:
  - mirage-xen-minios>=0.7.0 is not available because your system doesn't comply with os = "linux".
No solution found, exiting
'unset TESTS; OPAMYES=1 export OPAMYES; set -ue; opam install mirage-xen-posix --deps-only' exited 3. Terminating with 3
Command exited with code 3
```

**Comment by yomimono** [comment]
@djs55 did compiling mirage-xen on Windows work before, or was the appveyor test just building mirage-unix?

**Comment by djs55** [comment]
I believe it was Unix only. Perhaps it broke because the CI script was modified? We should probably git clone the `ocaml-ci-scripts` repo so we can see in the log what revision it's using :/

**Comment by yomimono** [comment]
OK, in that case I'll just remove the `EXTRA_DEPS` I inserted to make it build the other packages and the previous behavior will be restored.

Looking at the changelog in ocaml-ci-scripts would've been a sensible place to start, but I'd been trained out of it by the number of times that some change to `appveyor.yml` itself was required because of an upstream change in cygwin or something...
