### ISSUE TITLE
Update dtoa.c in xen-posix/ to correct string_of_float operation

### ISSUE THREAD

**Issue by mato** [mirage/mirage-platform#198]
Now that I have a fix for mirage/ocaml-freestanding#16, I've also reproduced the problem with Tim's test code (https://github.com/mirage/ocaml-freestanding/issues/16#issue-223060795) and can confirm that it exists on Xen.

The fix is to update `xen-posix/src/dtoa.c` to the version used by ocaml-freestanding, see mirage/ocaml-freestanding#28 for details.

**Comment by hannesm** [comment]
in the new world, where the mirage-xen path uses ocaml-freestanding as well (not yet implemented), there's no need anymore for mirage-xen-posix.  closing since the ocaml-freestanding rework will happen sooner than upgrading dtoa.c.  please reopen/comment if you disagree.
