### ISSUE TITLE
Opam2: Calling opam config exec -- ocamlfind query foo fails in the sandbox

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-platform#200]
The build script calls `opam config exec -- ocamlfind query foo` and this fails in opam2 because ~/opam/log/ is read-only in the sandbox. I'm not sure if I should file this as a bug in opam or here. Filing it here for now.

**Comment by samoht** [comment]
@rjbou said

> during build, `OPAMROOT` is not binded. As usually it is in `$HOME`, which is binded `ro`. At build stage, opam should not be invoked, especially with a command that could change change opam state (that needs `OPAMROOT` to be `rw` binded). Needed variables can be found in the environment, defined/found in the opam file and transmitted, or set at this stage.

**Comment by samoht** [comment]
So I am not sure why we are using `opam config exec` here, this should probably be removed.

**Comment by reynir** [comment]
I had the same thought initially. I made a quick PR for this :-)
