### ISSUE TITLE
Remove dependency on xenstore

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-platform#90]
Now that blkif and netif are out-of-tree, it should be possible to remove the dependency on xenstore. We would need to add some kind of pre-suspend hook (xenstore is the only service which is shutdown pre-suspend, everything else just re-issues requests post-resume); and functorise netif over xenstore (like blkif).

**Comment by hannesm** [comment]
copied over to https://github.com/mirage/mirage-xen/issues/3 - the new home of mirage-xen
